apiVersion: apps/v1
kind: Deployment

metadata: 
  name: online-shop-deployment
  namespace: online-shop
  labels:
    app: online-shop

spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: online-shop

  template:
    metadata:
      name: online-shop
      labels: 
        app: online-shop

    spec:
      containers:
      - name: online-shop-container
        image: subhik66/online-shop
        ports:
          - containerPort: 3000  
