apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod
  namespace: nginx-ns  # Deploying in the 'nginx-namespace'
  labels:
    app: nginx

spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80  
