apiVersion: v1
kind: Service

metadata:
  name: online-shop-svc
  namespace: online-shop
    
spec: 
  selector: 
    app: online-shop

  ports: 
    - protocol: TCP
      port: 3000
      targetPort: 3000

